# package name
name: com.appalachia.unity3d.editor.preferences.easy
# package display name
displayName: Easy Editor Preferences for Unity3D
# package description
description: Automatically creates, updates, and draws custom Editor Preferences in the Settings window. Supports bool, float, int, string, as well as enums (int-backed) and color.
# repository url
repoUrl: 'https://github.com/AppalachiaInteractive/com.appalachia.unity3d.editor.preferences.easy'
# forked repository url
parentRepoUrl: null
# spdx license id
licenseSpdxId: MIT
# license name
licenseName: MIT License
# list of topic slugs
topics:
  - utilities
# Filter Git tags based on prefix. Used by monorepos to separate pacakges
gitTagPrefix: ''
# A regular expression to ignore Git tags
gitTagIgnore: ''
# Minimal version to build
minVersion: '0.2.0'
# featured image
image: 'https://github.com/AppalachiaInteractive/com.appalachia.unity3d.editor.preferences.easy/raw/main/media/icon_social.png'
# featured image fit mode: cover (default) or contain
imageFit: cover
# readme path
readme: 'main:README.md'
# package hunter name (github username)
hunter: ChristopherSchubert